server:
  port: 8080  #端口
spring:
  application:
    name: api_zuul_server #服务名称
    #zipkin配置
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web # 数据的传输方式,以http的形式向server端发送数据
  sleuth:
    sampler:
      probability: 1 #采用比
zuul:
  routes:
    #商品微服务
#    product-service: # 路由id,随便写
#      path: /product-service/** #映射路径  # localhost:8080/product-service/sxxxxsd
     #url: http://127.0.0.1:9201 # 映射路径对应的实际微服务url地址
#      serviceId: service-product
     #如果路由id和对应的微服务的serviceId一致的话
      service-product: /product-service/**
     #zuul中的默认路由配置
     #如果当前的微服务名称 service-product,默认的请求映射路径 /product-service/**
     # service-order/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
  instance:
    prefer-ip-address: true # 使用ip地址注册